Pastry/Models/Treats.cs
using System.Collections.Generic;

namespace Pastry.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<TreatFlavor>();
    }

    public int TreatId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<TreatFlavor> JoinEntities { get; set; }
  }
}

Pastry/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Pastry.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Pastry.Controllers
{
  public class TreatsController : Controller
  {
    private readonly PastryContext _db;

    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PastryContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.OrderBy(treat => treat.Name).ToList();
      return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      bool exists = _db.Treats.Any(t => t.Name == treat.Name);
      if (!exists)
      {
        _db.Treats.Add(treat);
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.JoinEntities)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.UserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      return View(thisTreat);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      bool used = _db.TreatFlavor.Where(t => t.TreatId == treat.TreatId).Any(f => f.FlavorId == FlavorId);
      if (FlavorId != 0 && !used)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TreatId });
    }
  }
}

Pastry/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Treat

<h2>Add a flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" class="button"  value="Save" />
}

<p class="button">@Html.ActionLink("Back to list", "Index")</p>

Pastry/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Treat

<h4>Add a new treat</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @required = "required", @class="input"})
  <input type="submit" class="button"  value="Add new treat" />
}
<p class="button">@Html.ActionLink("Show all treats", "Index")</p>

Pastry/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Treat

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" class="button"  value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Pastry/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Treat;

<h2>@Model.Name</h2>
<hr />

@if(@Model.JoinEntities.Count == 0)
{
  <p>This treat has no specific flavors</p>
}
else
{
  <h4>Flavors:</h4>
  <ul class="details">
  @if (User.Identity.IsAuthenticated)
  {
    @foreach(var join in Model.JoinEntities)
    {
      <li>
        @using (Html.BeginForm("DeleteFlavor", "Treats"))
        {
          @Html.Hidden("joinId", @join.TreatFlavorId)
          <input type="submit" value="X" class="delete" />
        }
        @join.Flavor.Name
      </li>
    }
  }
  else 
  {
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Flavor.Name</li>
    }
  }
  
  </ul>
}

@if (User.Identity.IsAuthenticated)
{
  <p class="button">@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })</p>
  <p class="button">@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
  <p class="button">@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>
}

<p class="button">@Html.ActionLink("Back to treats", "Index")</p>

Pastry/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Treat

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "input", value = @Model.Name})

  <input type="submit" class="button"  value="Save" />
}
<p class="button">@Html.ActionLink("Back to list", "Index")</p>

Pastry/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Pastry.Models;

<h1>Treats</h1>

@if (Model.Count != 0)
{
  <ul>
    @foreach(Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
}
else
{
  <h3>No treats have been added yet!</h3>
}

@if (User.Identity.IsAuthenticated)
{
  <p class="button">@Html.ActionLink("Add new treat", "Create")</p>
}