Pastry/Models/Flavor.cs
using System.Collections.Generic;

namespace Pastry.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.JoinEntities = new HashSet<TreatFlavor>();
    }

    public int FlavorId { get; set; }
    public string Name { get; set; }
    public virtual ApplicationUser User { get; set; }

    public virtual ICollection<TreatFlavor> JoinEntities { get; }
  }
}

Pastry/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Pastry.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Pastry.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly PastryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PastryContext db)
    {
      _userManager = userManager;
      _db = db;
    }


    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.OrderBy(flavor => flavor.Name).ToList();
      return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
      bool exists = _db.Flavors.Any(f => f.Name == flavor.Name);
      if (!exists)
      {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.UserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      return View(thisFlavor);
    }
    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }
    [Authorize]
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      bool used = _db.TreatFlavor.Where(f => f.FlavorId == flavor.FlavorId).Any(t => t.TreatId == TreatId);
      if (TreatId != 0 && !used)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }
    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.FlavorId });
    }
  }
}

Pastry/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Flavor

<h2>Add a treat</h2>

<h4>Add a treat to this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")

  <input type="submit" class="button"  value="Save" />
}

<p class="button">@Html.ActionLink("Back to list", "Index")</p>

Pastry/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Flavor

<h4>Add a new flavor</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @required = "required", @class="input"})

  <input type="submit" class="button"  value="Add new flavor" class="btn btn-default" />
}
<p class="button">@Html.ActionLink("Show all flavors", "Index")</p>

Pastry/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" class="button"  value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Pastry/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Flavor

<h2>@Model.Name Flavor</h2>
<hr />

@if(@Model.JoinEntities.Count == 0)
{
  <p>There are no treats with this Flavor</p>
}
else
{
  <h4>Treats with this Flavor:</h4>
  <ul class="details">
  @if (User.Identity.IsAuthenticated)
  {
    @foreach(var join in Model.JoinEntities)
    {
      <li>
        @using (Html.BeginForm("DeleteTreat", "Flavors"))
        {
          @Html.Hidden("joinId", @join.TreatFlavorId)
          <input type="submit" value="X" class="delete" />
        }
        @join.Treat.Name
      </li>
    }
  } 
  else 
  {
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Treat.Name</li>
    }
  }
  </ul>
}

@if (User.Identity.IsAuthenticated)
{
  <p class="button">@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
  <p class="button">@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
  <p class="button">@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
}

<p class="button">@Html.ActionLink("Back to list", "Index")</p>

Pastry/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Pastry.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "input", value = @Model.Name})
  <input type="submit" class="button"  value="Save" />
}

<p class="button">@Html.ActionLink("Back to list", "Index")</p>

Pastry/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Pastry.Models;

<h1>Flavors</h1>

@if (Model.Count != 0)
{
  <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId })</li>
    }
  </ul>
} 
else
{
  <h3>No flavors have been added yet!</h3>
}

@if (User.Identity.IsAuthenticated)
{
  <p class="button">@Html.ActionLink("Add new flavor", "Create")</p>
}